### ISSUE TITLE
RpgWord does not work

### ISSUE THREAD

**Issue by atalaminos** [RSamaium/RPG-JS#101]
Hello

I am trying to change direction and move players with RpgWorld (https://docs.rpgjs.dev/classes/world.html#api) but the changes are not reflected in the game. Some help? Thanks

```typescript
app.get('/players', (req, res) => {
  const players = RpgWorld.getPlayers() ;
  players[0].changeDirection(Direction.Right);
  res.json(players.length);
})
```

**Comment by RSamaium** [comment]
Thanks for the feedback. The problem was twofold:

1) The direction is not performed on the client side if the player positions do not change
2) The modification in the players table does not send the data to the client

The correction has been made and is available in version 3.0.0-alpha.13

To update, change the version of the packages in `package.json` and reinstall with the command `npm install`

https://github.com/rpgjs/template/blob/master/package.json

**Comment by atalaminos** [comment]
Excelent response!

I manage to move the character correctly by modifying the properties of player[0].position and check if there is a collision with the isCollided. Thank you! Just note that the move and moveByDirection properties do not have the expected behavior. The movement is not fluid and sometimes the character backs up or performs strange movements. 

My project idea uses RpgWorld constantly. I will try to fix it on my own if I can. It seems to me a very powerful class. Thanks

**Comment by atalaminos** [comment]
Strange behavior happens with position as well. It's weird because it doesn't always happen and sometimes even two characters appear on the screen :(

I am trying to move the character from a url, but there is no way

```typescript
app1.get('/moveLeft', (req, res) => {
      
    const position = {...players[0].position}
    position.x -= 12;
  
    if (!player.isCollided(position)) {
      
      players[0].position.x -= 12;
      players[0].changeDirection(Direction.Left);
    }
    res.json({});
})
```

**Comment by RSamaium** [comment]
On my side, it moves the player well (but I see that you don't have a declared player variable, would it be your concern?)


To move a character on the map, use the method moveRoutes

```ts
import { RpgWorld, Move } from '@rpgjs/server'

app.get('/moveLeft', (req, res) => {
    const players = RpgWorld.getPlayers()
    const player =  players[0] // first player
    //  Move.left(4) = 4 times the speed of the character (if the speed is 3 then it will move 12px)
    player.moveRoutes([ Move.left(4) as any ]) // Type problem (to correct on my side)
    res.json({});
})
```

https://docs.rpgjs.dev/commands/move.html#movement-commands

Yes, the character movement is strange but it's because of the interpolation on the client side. I look at this (I open a new issue)

**Comment by atalaminos** [comment]
Thanks again for your help. Perhaps the character could move exactly the same as moving with the arrow keys (3 pixels). That move is perfect and fluid. It would be ideal if it could be done with a method from the server. It is what I am trying to implement, but I have not been able at the moment

**Comment by RSamaium** [comment]
The movement is corrected in the latest version

https://github.com/RSamaium/RPG-JS/issues/104
