### ISSUE TITLE
Player movement jittering issue

### ISSUE THREAD

**Issue by kepoly** [RSamaium/RPG-JS#127]
Please see video attached: 
https://streamable.com/n50q4g

When a player finishes the desired path the sprite jitters.

**Comment by RSamaium** [comment]
Thanks for the feedback, I'm looking into it

**Comment by cryptonft** [comment]
I believe this is due to lag, it happens a lot more (jumping back and forth) in extreme situations. 

https://user-images.githubusercontent.com/80640570/155290618-91c123da-5697-4014-a4c7-5e038f93c544.mp4

**Comment by RSamaium** [comment]
In fact, it is because the server is ahead of the client. It is enough that the client's FPS is slower (40 FPS for example), while the server is at 60 FPS, then the reconciliation between server and client will produce the jumps.

To fix the bug, we have to add the deltaTime notion on the positions in order to take into account the FPS lag. 

For the moment, it is under consideration ;) But classified in priority in the corrections for the next release

**Comment by kepoly** [comment]
Thanks for the update @RSamaium ETA on next release?

**Comment by RSamaium** [comment]
For the moment, no precision on a release date :)

**Comment by RSamaium** [comment]
Fixed in the latest version (beta.6)
